name: Better Create Release
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Me The Money
        run: |
          echo ${{ toJson(github) }}

